name: PRChanged
# WARNING!  The run name MUST start with "PR <pr_number>".
# The accompanying privleged workflow parses this to find
# the PR number.  It's the only reliable way it can get it.
run-name: "PR ${{ github.event.number }} Changed by ${{ github.actor }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

jobs:

  Setup:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        env:
          TEST_FROM_VARS: ${{ fromJSON(vars.TEST_BOOLEAN || false) && '--upgrade-note' || '' }}
        run: |
          # Wait then get testsuite PR
          echo "AAA ${TEST_FROM_VARS} BBB"
