name: PRChanged
# WARNING!  The run name MUST start with "PR <pr_number>".
# The accompanying privleged workflow parses this to find
# the PR number.  It's the only reliable way it can get it.
run-name: "PR ${{ github.event.number }} Changed by ${{ github.actor }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  actions: read
#  attestations: read|write|none
  checks: read
  contents: read
#  deployments: read|write|none
#  id-token: write|none
  issues: read
#  discussions: read|write|none
#  packages: read|write|none
#  pages: read|write|none
  pull-requests: write
#  repository-projects: read|write|none
#  security-events: read|write|none
  statuses: read

env:
  REPO:            ${{ github.repository }}
  REPO_DIR:        ${{ github.workspace }}/${{ github.event.repository.name }}
  REPO_ORG:        ${{ github.event.repository.owner.login }}
  PR_NUMBER:       ${{ github.event.number }}
  BASE_BRANCH:     ${{ github.event.pull_request.base.ref }}
  WORKFLOW_NAME:   ${{ github.workflow }}
  WORKFLOW_RUN_ID: ${{ github.run_id }}
  GH_TOKEN:        ${{ github.token }}

jobs:
  PRChanged:
    name: "run-check"
    concurrency:
      group: check-${{ github.base_ref }}-${{ github.ref_name }}
      cancel-in-progress: true
    uses: ./.github/workflows/AsteriskPRChanged.yml

  Cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: CleanupStep
        run: |
          gh --repo ${REPO} pr edit ${PR_NUMBER} --add-label duplicate
